name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [16.x]
  steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - name: yarn install and build
      run: |
        yarn 
        yarn build
